<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>{{ $title ?? 'Document' }}</title>
    <style>
        @page {
            size: A4;
            margin: 32mm 20mm 25mm 20mm;
        }

        body {
            font-family: DejaVu Sans, sans-serif;
            font-size: 11pt;
            color: #1f2933;
            line-height: 1.35;
        }

        h1, h2, h3, h4 {
            margin: 0 0 4pt;
            font-weight: 600;
        }

        .small { font-size: 9pt; color: #6b7280; }
        .muted { color: #6b7280; }
        .text-right { text-align: right; }
        .text-center { text-align: center; }
        .mt-1 { margin-top: 4pt; }
        .mt-2 { margin-top: 8pt; }
        .mt-3 { margin-top: 12pt; }
        .mb-0 { margin-bottom: 0; }
        .mb-1 { margin-bottom: 4pt; }
        .mb-2 { margin-bottom: 8pt; }
        .mb-3 { margin-bottom: 12pt; }

        .section-title {
            font-size: 9pt;
            letter-spacing: 0.12em;
            text-transform: uppercase;
            color: #4b2b24;
            margin-top: 10pt;
            margin-bottom: 4pt;
        }

        .divider {
            border-top: 0.4pt solid #d1d5db;
            margin: 3pt 0 6pt;
        }

        /* Stable key–value rows: no flex, just inline blocks */
        .kv-row {
            font-size: 10.5pt;
            padding: 1pt 0;
            border-bottom: 0.3pt solid #e5e7eb;
        }

        .kv-key {
            display: inline-block;
            min-width: 32%;
            max-width: 32%;
            color: #4b5563;
        }

        .kv-value {
            display: inline-block;
            width: 66%;
        }

        .note-block {
            font-size: 9pt;
            color: #4b5563;
            margin-top: 4pt;
        }

        .signature-block {
            margin-top: 18pt;
            font-size: 9pt;
        }

        .signature-line {
            margin-top: 18pt;
            border-top: 0.4pt solid #374151;
            width: 160pt;
        }

        .page-header {
            position: fixed;
            top: 12mm;
            left: 20mm;
            right: 20mm;
            font-size: 9.5pt;
        }

        .page-header-table {
            width: 100%;
            border-collapse: collapse;
        }

        .page-header-table td {
            vertical-align: top;
        }

        .header-name {
            font-weight: 600;
            letter-spacing: 0.08em;
            text-transform: uppercase;
            color: #4b2b24;
        }

        .header-subtitle {
            font-size: 9pt;
            color: #4b5563;
        }

        .header-contact {
            font-size: 8.5pt;
            color: #4b5563;
            text-align: right;
            line-height: 1.4;
        }

        .header-divider {
            position: fixed;
            top: 28mm;
            left: 20mm;
            right: 20mm;
            border-top: 0.4pt solid #d1d5db;
        }

        .page-footer {
            position: fixed;
            bottom: 10mm;
            left: 20mm;
            right: 20mm;
            font-size: 8.5pt;
            color: #6b7280;
        }

        .content {
            margin-top: 2mm;
        }
    </style>
</head>
<body>
@php($generatedAt = $generatedAt ?? now())
@php($generatedBy = $generatedBy ?? (auth()->user()->name ?? 'System'))

<div class="page-header">
    <table class="page-header-table">
        <tr>
            <td style="width:26mm;">
                <img src="{{ public_path('assets/kunjachanMissionaryLogo.png') }}" alt="Logo" style="height:18mm;">
            </td>
            <td>
                <div class="header-name">KUNJACHAN MISSIONARY BHAVAN</div>
                <div class="header-subtitle">Psycho-social rehabilitation and care services</div>
            </td>
            <td class="header-contact">
                Ramapuram, Idiyanal P.O, Kottayam, Kerala - 686576<br>
                E-mail: kunjachanmissionary@gmail.com<br>
                Ph: 04822 260435, 260835 · Mob: 9048864128
            </td>
        </tr>
    </table>
</div>
<div class="header-divider"></div>

<div class="page-footer">
    <table style="width:100%;border-collapse:collapse;">
        <tr>
            <td style="text-align:left;">
                Generated on: {{ $generatedAt->format('Y-m-d H:i') }} · Generated by: {{ $generatedBy }}
            </td>
            <td style="text-align:right;">
                Page {PAGE_NUM} of {PAGE_COUNT}
            </td>
        </tr>
    </table>
</div>

<main class="content">
    @yield('content')
</main>
</body>
</html>
